### ISSUE TITLE
Rename "Applications" "API access tokens" (v12)

### ISSUE THREAD

**Issue by liotf** [materialscloud-org/big-map-archive#39]
In the current version of BIG-MAP Archive in production, there is a "tab" named "API access tokens" (see https://archive.big-map.eu/account/settings/applications/). However, on the branch francois/upgrade_v12.0.0b2.dev36, this tab is labelled "Applications".

**Comment by vgranata** [comment]
It was decided to leave the label "Applications". The tutorial: https://github.com/materialscloud-org/big-map-archive/blob/master/user_training/getting_started_with_big-map-archive.md will be updated.
