### ISSUE TITLE
Show "Collaborate" button (v12)

### ISSUE THREAD

**Issue by liotf** [materialscloud-org/big-map-archive#40]
In the current version of BIG-MAP Archive in production, there is a button labelled "Collaborate" (see https://archive.big-map.eu/records/<record_id> for a user who owns the shared record). 

![collaborate_button](https://github.com/materialscloud-org/big-map-archive/assets/44171110/120e6fd7-bb42-458c-9f02-55769b0b2908)
![panel_to_get_link](https://github.com/materialscloud-org/big-map-archive/assets/44171110/6ba431c8-a298-4fa4-b52b-7d9b553f4b65)

However, on the branch francois/upgrade_v12.0.0b2.dev36, such a button has been hidden/removed because the contents of the panel for getting the link was not enough user-friendly.

**Comment by vgranata** [comment]
These commits: 
30bed6d9e83dd214faaba488551f6bc0a0c1aabe
1b5905fbf946797cc5ddf528a417cac39106ff3a
b09afbf44a743c9647244a7a26532d52e8541b44
891f0082643192847170d6c65f855c0a640ce05c
solved the issue #40

The modal to create access links it is now available also on the upload form.
