### ISSUE TITLE
Change error messages related to upload form (v12)

### ISSUE THREAD

**Issue by liotf** [materialscloud-org/big-map-archive#41]
On the branch francois/upgrade_v12.0.0b2.dev36, if a user tries to share a draft that has validation errors, the following error message may be shown: "The draft was not submitted for review". 

![error_message](https://github.com/materialscloud-org/big-map-archive/assets/44171110/323041f8-3bb7-48b8-8bb3-64772e64ffef)

Since there is no review process, I would recommend replacing the error message by "The draft was not privately shared with the selected community".

**Comment by vgranata** [comment]
This commit b693fd0fd59b8955c2ef3b2dda2c5bf94772c8f2 solved the issue #41
