### ISSUE TITLE
Fix responsive design issues (v12)

### ISSUE THREAD

**Issue by liotf** [materialscloud-org/big-map-archive#42]
On the branch francois/upgrade_v12.0.0b2.dev36, reducing the width of the viewport below 1300 px leads to an ugly layout, where the two logos are close to each other.

![viewport_larger_than_1300px](https://github.com/materialscloud-org/big-map-archive/assets/44171110/b107df01-f7b3-4c9a-a4b1-8bdb52008448)
![viewport_smaller_than_1300px](https://github.com/materialscloud-org/big-map-archive/assets/44171110/6b1f3ab0-c389-4203-99d8-9f569ad3f257)

**Comment by vgranata** [comment]
The commit 19dc4e4b0411075ed37e5670e7d0c117076be45e solved the issue #42
