### ISSUE TITLE
Finish testing API endpoints & update BIG-MAP Archive (v12)

### ISSUE THREAD

**Issue by liotf** [materialscloud-org/big-map-archive#43]
For the branch francois/upgrade_v12.0.0b2.dev36, I have tested many API endpoints according to their presentation order in the InvenioRDM documentation (see https://inveniordm.docs.cern.ch/reference/ and click "REST API").

I have tested communities-related endpoints (see https://inveniordm.docs.cern.ch/reference/rest_api_communities/) and shared records-related endpoints (see https://inveniordm.docs.cern.ch/reference/rest_api_drafts_records/) with success. More details regarding the tests can be found in the README.md file (see https://github.com/materialscloud-org/big-map-archive/blob/francois/upgrade_v12.0.0b2.dev36/README.md).

I have started to test drafts-related API endpoints. However, modifying BIG-MAP Archive appears to be necessary to fix issues (e.g., it is possible to create a draft with an invalid value for a reference scheme) and to avoid users to publish a draft outside any community or with a community that they do not belong to.

More work is needed to complete the tests and make sure that requests get suitable responses.

Please find as an attachment the collection of requests that I built to test BIG-MAP Archive using Postman. 

[BIG-MAP Archive API.postman_collection.json](https://github.com/materialscloud-org/big-map-archive/files/13854985/BIG-MAP.Archive.API.postman_collection.json)

**Comment by vgranata** [comment]
Tests for records, communities, members, requests, reviews and secret links are in [/tests](https://github.com/materialscloud-org/big-map-archive/tree/develop_v12/tests).
